# Usar una imagen base de Python
FROM python:3.11-slim

# Setear el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar requirements (desde la raíz) e instalarlos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del proyecto
COPY . .

# Setear el PYTHONPATH
ENV PYTHONPATH=.

# El comando que corre este contenedor
CMD ["celery", "-A", "src.worker.celery_app", "worker", "--loglevel=info", "--pool=threads"]