services:
  # 1) Echo HTTP — refleja lo que envías (headers/body)
  echo:
    image: ealen/echo-server:latest
    container_name: demo_echo
    ports:
      - "8080:80"
    restart: unless-stopped


  # 3) Daytime — servidor TCP que devuelve la hora en texto
  #    (instala netcat y tzdata al iniciar; ajusta TZ si querés otra zona)
  daytime:
    image: alpine:3.20
    container_name: demo_daytime
    environment:
      - TZ=America/Argentina/Mendoza
    command: >
      sh -c "
      apk add --no-cache tzdata netcat-openbsd &&
      ln -sf /usr/share/zoneinfo/${TZ:-UTC} /etc/localtime &&
      echo ${TZ:-UTC} > /etc/timezone &&
      while true; do
        date '+%Y-%m-%d %H:%M:%S %Z' | nc -l -p 1313 -q 0;
      done"
    ports:
      - "1313:1313"
    restart: unless-stopped


  # 4) MailHog — SMTP de prueba + UI web
  mailhog:
    image: mailhog/mailhog:latest
    container_name: demo_mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped
