services:
  server:
    build: ./server/  # Asume que tu server.py y Dockerfile están en una carpeta 'server'
    ports:
      # Mapea el puerto del host al contenedor, especificando UDP
      - "9999:9999/udp"
    container_name: mi_servidor_de_hora

  client:
    build: ./cliente/  # Asume que tu client.py y Dockerfile están en una carpeta 'client'
    environment:
      # Aquí pasamos las variables de entorno al cliente
      - SERVER_HOST=server
      - SERVER_PORT=9999
    # Asegura que el cliente inicie después del servidor
    depends_on:
      - server
    container_name: mi_cliente_de_hora